openapi: 3.0.0
servers:
  - description: json server
    url: localhost:3000

info:
  description: This is the API for the blog
  version: "1.0.0"
  title: Blog API

tags:
  - name: posts

paths:
  /posts:
    get:
      tags:
        - posts
      summary: Get all posts
      operationId: getPosts
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      tags:
        - posts
      summary: Add a post
      operationId: addPost
      requestBody:
        $ref: "#/components/requestBodies/Post"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /posts/{id}:
    get:
      tags:
        - posts
      summary: Get one post
      operationId: getPost
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
    put:
      tags:
        - posts
      summary: Edit a post
      operationId: editPost
      requestBody:
        $ref: "#/components/requestBodies/Post"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        date:
          type: string
          format: date
        content:
          type: string

  requestBodies:
    Post:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Post"
      description: Post object that needs to be added
      required: true
