/**
 * Blog API
 * This is the API for the blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Post { 
    id?: string;
    title?: string;
    date?: string;
    content?: string;
}

